Algoritmo "lista1 exercicio1"
//  
//  
// Disciplina   : LPOO
// Professor   : Aldo Henrique
// Autor(a)    : Rafael Sampaio Tibery Silva
// Data atual  : 20/02/2019
Var
n1, n2, soma, dif, pro, med: inteiro
Inicio
leia(n1)
leia(n2)
soma<- n1 + n2
escreva("resultado da soma", soma)
dif<- n1 - n2
escreva("resultado de dif", dif)
pro<- n1 * n2
escreva("resultado de pro", pro)
med<- (n1 + n2)\ 2
escreva("resultado de med", med)
Fimalgoritmo